Repository mock-foundation/moc, pull requests merged in 2022-09, with the labels that each got.

#144 Vertical tab switcher + folders settings developer info
  Backend/Sources/Backend/Services/Td/Settings/TdFoldersPrefService.swift
  Moc.xcodeproj/project.pbxproj
  Shared/Commands/AppCommands.swift
  Shared/MocApp+Injection.swift
  Shared/View Models/Chat/ChatViewModel.swift
  Shared/View Models/MainViewModel.swift
  Shared/Views/Chat/ChatView.swift
  Shared/Views/Chat/Message/MessageView+Photo.swift
  Shared/Views/Common/FolderItem.swift
  Shared/Views/Common/View+Faded.swift
  Shared/Views/RootView.swift
  Shared/Views/Settings/FoldersPrefView.swift
  Storage/Sources/Storage/StorageService.swift
  macOS/Views/View+IntrospectNSSplitView.swift
Labels: enhancement, ui, OS: all, ux

#146 What's New
  Moc.xcodeproj/project.pbxproj
  Shared/MocApp+Injection.swift
  Shared/Utils/View+SidebarSize.swift
  Shared/Views/Chat/ChatView.swift
  Shared/Views/RootView.swift
  Shared/Views/WhatsNew.swift
Labels: enhancement, ui, OS: all, ux

#147 fix: crash on viewing albums
  Shared/Views/Chat/Message/MessageView+Album.swift
Labels: ui, OS: all, critical, crash

#153 Members in Chat Inspector
  Moc.xcodeproj/project.pbxproj
  Shared/Keys/ScrollOffsetPreferenceKey.swift
  Shared/Keys/SizePreferenceKey.swift
  Shared/View Models/Chat/ChatInspectorViewModel.swift
  Shared/Views/Chat/ChatInspector.swift
Labels: enhancement, OS: all, ux

#151 Better album layout for macOS Ventura and iPadOS 16
  Backend/Sources/Backend/TdHandler.swift
  Moc.xcodeproj/project.pbxproj
  Shared/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_128x128@2x.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_16x16.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_16x16@2x.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_256x256.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_256x256@2x.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_32x32.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_32x32@2x.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_512x512.png
  Shared/Assets.xcassets/AppIcon.appiconset/icon_512x512@2x.png
  Shared/Layouts/MediaAlbum.swift
  Shared/View Models/MainViewModel.swift
  Shared/Views/AsyncTd/AsyncTdFile.swift
  Shared/Views/Chat/Message/MessageView+Album.swift
  Shared/Views/Chat/Message/MessageView+Photo.swift
  Shared/Views/Chat/Message/MessageView+Video.swift
  Shared/WhatsNew.swift
  Utilities/Sources/Utilities/Typealiases.swift
  Utilities/Sources/Utilities/URL+Thumbnail.swift
Labels: enhancement, ui, OS: all
