Repository mock-foundation/moc, pull requests merged in 2022-07, with the labels that each got.

#83 Replies
  Backend/Sources/Backend/Services/Mock/MockChatService.swift
  Backend/Sources/Backend/Services/Protocols/ChatService.swift
  Backend/Sources/Backend/Services/Td/TdChatService.swift
  Moc.xcodeproj/project.pbxproj
  Moc/Models/Message.swift
  Moc/Models/ReplyMessage.swift
  Moc/Utils/View+If.swift
  Moc/ViewModels/ChatViewModel.swift
  Moc/Views/Chat/ChatView.swift
  Moc/Views/Chat/Message/Document/MessageView+Document.swift
  Moc/Views/Chat/Message/MessageView+Document.swift
  Moc/Views/Chat/Message/MessageView+Message.swift
  Moc/Views/Chat/Message/MessageView+Reply.swift
  Moc/Views/Chat/Message/MessageView.swift
  Utilities/Sources/Utilities/Constants.swift
  macOS/Views/LottieView.swift
Labels: enhancement, ui, OS: all

#87 Add Networking module
  Moc.xcodeproj/project.pbxproj
  Moc/ViewModels/EmojiViewModel.swift
  Networking/.gitignore
  Networking/Package.swift
  Networking/README.md
  Networking/Sources/Networking/Base/Endpoint.swift
  Networking/Sources/Networking/Base/HTTPClient.swift
  Networking/Sources/Networking/Base/HTTPMethods.swift
  Networking/Sources/Networking/Base/RequestError.swift
  Networking/Sources/Networking/Services/Emoji/EmojiModel.swift
  Networking/Sources/Networking/Services/Emoji/EmojiNetworking.swift
  Networking/Sources/Networking/Services/Emoji/EmojiService.swift
  Networking/Tests/NetworkingTests/NetworkingTests.swift
Labels: enhancement, OS: all, internal

#93 Tests for Networking module
  Networking/Package.swift
  Networking/Sources/Networking/Services/Emoji/EmojiModel.swift
  Networking/Sources/Networking/Services/Emoji/EmojiService.swift
  Networking/Tests/NetworkingTests/EmojiTests/EmojiMock.swift
  Networking/Tests/NetworkingTests/EmojiTests/EmojiTests.swift
  Networking/Tests/NetworkingTests/JSON/emoji.json
  Networking/Tests/NetworkingTests/Mockable.swift
  Networking/Tests/NetworkingTests/NetworkingTests.swift
Labels: enhancement, OS: all, internal

#91 TDLibKit Update
  Backend/Package.swift
  Backend/Sources/Backend/Services/Mock/MockChatService.swift
  Backend/Sources/Backend/Services/Mock/MockLoginService.swift
  Backend/Sources/Backend/Services/Mock/MockMainService.swift
  Backend/Sources/Backend/Services/Mock/Settings/MockAccountsPrefService.swift
  Backend/Sources/Backend/Services/Protocols/ChatService.swift
  Backend/Sources/Backend/Services/Protocols/LoginService.swift
  Backend/Sources/Backend/Services/Protocols/MainService.swift
  Backend/Sources/Backend/Services/Protocols/Service.swift
  Backend/Sources/Backend/Services/Protocols/Settings/AccountsPrefService.swift
  Backend/Sources/Backend/Services/Protocols/Settings/FoldersPrefService.swift
  Backend/Sources/Backend/Services/Td/Settings/TdAccountsPrefService.swift
  Backend/Sources/Backend/Services/Td/Settings/TdFoldersPrefService.swift
  Backend/Sources/Backend/Services/Td/TdChatService.swift
  Backend/Sources/Backend/Services/Td/TdLoginService.swift
  Backend/Sources/Backend/Services/Td/TdMainService.swift
  Backend/Sources/Backend/TdHandler.swift
  Backend/Sources/Backend/Utils/CachingChatList.swift
  Backend/Sources/Backend/Utils/Chat+Mock.swift
  Backend/Sources/Backend/Utils/NotificationKeys.swift
  Moc.xcodeproj/project.pbxproj
  Moc/MocApp+Injection.swift
  Moc/Utils/MessageContent+Preview.swift
  Moc/Utils/TDLibKit+Protocols.swift
  Moc/ViewModels/Chat/ChatViewModel+Interactions.swift
  Moc/ViewModels/Chat/ChatViewModel+Updates.swift
  Moc/ViewModels/Chat/ChatViewModel.swift
  Moc/ViewModels/EmojiViewModel.swift
  Moc/ViewModels/MainViewModel.swift
  Moc/ViewModels/Settings/AccountsPrefViewModel.swift
  Moc/ViewModels/Settings/FoldersPrefViewModel.swift
  Moc/Views/AsyncTd/AsyncTdFile.swift
  Moc/Views/Chat/ChatView+InputField.swift
  Moc/Views/Chat/ChatView+Inspector.swift
  Moc/Views/Chat/Message/MessageView+Message.swift
  Moc/Views/Chat/Message/MessageView+Utils.swift
  Moc/Views/Chat/Message/MessageView.swift
  Moc/Views/ChatItemView.swift
  Moc/Views/Login/LoginView.swift
  Moc/Views/Settings/AccountsPrefView.swift
  Templates/AutoEquatable.stencil
  Templates/AutoHashable.stencil
  Utilities/Sources/Utilities/Constants.swift
  sourcery.sh
Labels: enhancement, OS: all, internal

#97 Scroll to bottom button hiding itself in the bottom
  Backend/Package.swift
  Caching/Package.swift
  Logs/Package.swift
  Moc.xcodeproj/project.pbxproj
  Moc/Keys/ChatListItemSelectedKey.swift
  Moc/Keys/ScrollOffsetPreferenceKey.swift
  Moc/ViewModels/Chat/ChatViewModel.swift
  Moc/Views/Chat/ChatView.swift
  Utilities/Package.swift
  Utilities/Sources/Utilities/SystemUtils.swift
  Utilities/Sources/Utilities/URL+Thumbnail.swift
Labels: bug, OS: all, ux

#100 Sidebar size system setting support
  Moc.xcodeproj/project.pbxproj
  Moc/Info.plist
  Moc/MocApp+Injection.swift
  Moc/Models/SidebarSize.swift
  Moc/Settings/DefaultKeys.swift
  Moc/ViewModels/MainViewModel.swift
  Moc/Views/ChatItemView.swift
  Moc/Views/Commands/About/AboutView.swift
  Moc/Views/ContentView.swift
  Moc/Views/FolderItemView.swift
  Utilities/Sources/Utilities/Constants.swift
Labels: enhancement, ui, OS: macos

#103 PR workflow
  .github/workflows/pr.yml
Labels: enhancement

#102 Fix session termination crash
  Backend/Package.swift
  Moc.xcodeproj/project.pbxproj
  Moc/ViewModels/MainViewModel.swift
  Moc/Views/ChatItemView.swift
  Moc/Views/ContentView.swift
Labels: enhancement, OS: all, internal
